#!/bin/sh

# Helper script that reads /etc/default/dump1090-fa
# and either starts dump1090-fa with the configured
# arguments, or exits with status 64 to tell systemd
# not to auto-restart the service.

if [ -f /etc/default/dump1090-fa ]
then
    . /etc/default/dump1090-fa
fi

if [ -f /var/cache/piaware/location.env ]
then
    . /var/cache/piaware/location.env
fi

if [ "x$ENABLED" != "xyes" ]
then
    echo "dump1090-fa not enabled in /etc/default/dump1090-fa" >&2
    exit 64
fi

if [ -n "$PIAWARE_LAT" -a -n "$PIAWARE_LON" ]
then
    POSITION="--lat $PIAWARE_LAT --lon $PIAWARE_LON"
fi

#Netcat can also be used to pipe data to file
#exec nc -lk localhost 30003 > /data/flight/1090/flightlog.txt &

#socat -u TCP4-LISTEN:30003,reuseaddr,fork OPEN:/tmp/test.log,creat,append
#socat -u TCP:localhost:30003 OPEN:/data/flight/1090/test.log,creat,append &


exec /usr/bin/dump1090-fa \
     $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $JSON_OPTIONS $POSITION \
     "$@" >> /data/flight/1090/$(date -u +"%Y%m%dT%H%M%S" )_flight.log 

# exec failed, do not restart
exit 64
